### ISSUE TITLE
throw's uncaught error on a squarespace rss feed

### ISSUE THREAD

**Issue by mattmarcum** [kiernanmcgowan/node-blindparser#13]
I was trying out blindparser and threw some podcasts at it and it crashes on this one: http://ember.land/?format=rss

Its a square-space generated feed so I think its probably rss compliant.  The error is: 
```
Unexpected close tag
Line: 10
Column: 7
Char: >
```
I think its having problems parsing the cdata.

**Comment by kiernanmcgowan** [comment]
Thanks for the report. Have you noticed it failing with any other feeds?

**Comment by kiernanmcgowan** [comment]
Thanks for finding this error, checkout `blindparser@0.2.0` for your fix.
